### ISSUE TITLE
Would it be possible to connect with stripe?

### ISSUE THREAD

**Issue by Polin2711** [https-eduardo/discord-pix-bot#5]
Would it be possible to connect with stripe?

**Comment by https-eduardo** [comment]
@Polin2711 Yes, its possible, you'll probably just need some adjusts.

**Comment by Polin2711** [comment]
How??

**Comment by https-eduardo** [comment]
@Polin2711 Well, this repo is just the discord bot, the integration (backend) is in this repo https://github.com/https-eduardo/pix-integration.

The integration is using Mercado Pago instead of Stripe, but you change the code to implement everything that you want.

**Comment by Polin2711** [comment]
Thx
